// Code generated by "stringer -type ErrCode -linecomment -output code_string.go"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_CODE_OK-0]
	_ = x[ERR_CODE_INVALID_PARAMS-1]
	_ = x[ERR_CODE_FAILED-2]
	_ = x[ERR_CODE_NO_RIGHTS-3]
}

const _ErrCode_name = "请求成功无效参数请求失败没有权限"

var _ErrCode_index = [...]uint8{0, 12, 24, 36, 48}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
